<a href="https://colab.research.google.com/github/jaewoong-87/deep_learning/blob/main/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

chain rule

In [1]:
class Mul():
  def __init__(self):
    self.x=None
    self.y=None

  def forward(self, x,y):
    self.x=x
    self.y=y
    result = x*y
    return result

  def backward(self, dresult):
    dx = dresult * self.y
    dy = dresult * self.x
    return dx, dy

In [3]:
class Add():
  def __init__(self):
    self.x=None
    self.y=None

  def forward(self, x, y):
    self.x = x
    self.y = y
    result = x+y
    return result

  def backward(self, dresult):
    dx = dresult * 1
    dy = dresult * 1
    return dx, dy

In [4]:
a, b, c = -1, 3, 4
x= Add()
y = Add()
f = Mul()

In [5]:
x_result =x.forward(a,b)
y_result =y.forward(b,c)

print(x_result)
print(y_result)
print(f.forward(x_result,y_result))

2
7
14


In [7]:
dresult = 1
dx_mul, dy_mul = f.backward(dresult)

da_add, db_add_1 = x.backward(dx_mul)
db_add_2, dc_add = y.backward(dy_mul)

print(dx_mul, dy_mul)
print(da_add)
print(db_add_1 + db_add_2)
print(dc_add)

7 2
7
9
2


backpropagation in sigmoid f

In [8]:
class Sigmoid:
  def __init__(self):
    self.out = None

  def forward(self, x):
    out = 1/(1+np.exp(-x))
    return out
  
  def backward(self, dout):
    dx = dout * (1.0 - self.out) * self.dout
    return

B.G in ReLU

In [9]:
class ReLU():

  def __init__(self):
    self.out =None
  
  def forward(self, x):
    self.mask = (x<0)
    out = x.copy()
    out[x<0] = 0
    return out

  def backward(self, dout):
    dout[self.mask] =0
    dx = dout
    return dx_mul

forward

In [11]:
import numpy as np

X = np.random.rand(3)
W = np.random.rand(3,2)
B = np.random.rand(2)

print(X.shape)
print(W.shape)
print(B.shape)


(3,)
(3, 2)
(2,)


In [12]:
Y = np.dot(X,W) + B
print(Y.shape)

(2,)


In [13]:
X = np.random.rand(3)
W = np.random.rand(2,2)
B = np.random.rand(2)

print(X.shape)
print(W.shape)
print(B.shape)

(3,)
(2, 2)
(2,)


In [14]:
Y = np.dot(X,W) + B
print(Y.shape)

ValueError: ignored

shape should be matched.

In [18]:
X = np.random.randn(2)
W = np.random.randn(2,3)
Y = np.dot(X,W)

print("X\n{}".format(X))
print("W\n{}".format(W))
print("Y\n{}".format(Y))

X
[0.40808478 1.01901049]
W
[[ 0.07682922  0.93430204  0.7910283 ]
 [-0.32949638  0.86242414  0.08597736]]
Y
[-0.30440743  1.26009368  0.41041844]


B.G

In [20]:
dL_dY = np.random.randn(3)
dL_dX = np.dot(dL_dY, W.T)
dL_dW = np.dot(X.reshape(-1,1), dL_dY.reshape(1,-1))

print("dL_dY\n{}".format(dL_dY))
print("dL_dX\n{}".format(dL_dX))
print("dL_dW\n{}".format(dL_dW))

dL_dY
[ 2.18101747 -0.5595502   0.13872834]
dL_dX
[-0.24548497 -1.18927946]
dL_dW
[[ 0.89004003 -0.22834392  0.05661292]
 [ 2.22247967 -0.57018752  0.14136564]]


B.G2

In [21]:
X = np.random.randn(2)
W = np.random.randn(2,3)
B = np.random.randn(3)
Y = np.dot(X,W) + B

print(Y)

[-5.15794952  1.32740988  1.161217  ]


In [22]:
dL_dY = np.random.randn(3)
dL_dX = np.dot(dL_dY, W.T)
dL_dW = np.dot(X.reshape(-1,1), dL_dY.reshape(1,-1))
dL_dB = dL_dY

print("dL_dY\n{}".format(dL_dY))
print("dL_dX\n{}".format(dL_dX))
print("dL_dW\n{}".format(dL_dW))
print("dL_dB\n{}".format(dL_dB))

dL_dY
[-0.61019158 -3.16255834  0.38681559]
dL_dX
[-4.9413117  -1.45815254]
dL_dW
[[-0.31382316 -1.62651223  0.1989403 ]
 [ 0.86573714  4.48702393 -0.54881227]]
dL_dB
[-0.61019158 -3.16255834  0.38681559]


In [23]:
class Layer():

  def __init__(self):
    self.W=np.random.randn(3,2)
    self.b = np.random.randn(2)
    self.x = None
    self.dW = None
    self.db = None
  
  def forward(self, x):
    self.x = x
    out = np.dot(x, self.W) + self.b
    return out

  def backward(self, dout):
    dx = np.dot(dout, self.W.T)
    self.dW = np.dot(self.x.T, dout)
    self.db = np.sum(dout, axis=0)
    return dx

In [24]:
np.random.seed(111)

layer = Layer()

In [25]:
X = np.random.rand(2,3)
Y = layer.forward(X)

print(X)

[[0.23868214 0.33765619 0.99071246]
 [0.23772645 0.08119266 0.66960024]]


In [26]:
dout = np.random.rand(2,2)
dout_dx = layer.backward(dout)

print(dout_dx)

[[-0.59898814  0.83225859 -0.61525238]
 [-0.48312871  0.65565961 -0.42154775]]


MNIST with B.G

In [27]:
import tensorflow as tf
import matplotlib.pyplot as plt
plt.style.use('seaborn-white')
from collections import OrderedDict

In [29]:
np.random.seed(42)

mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

num_classes = 10

11493376/11490434 [==============================] - 0s 0us/step


In [30]:
X_train, X_test = X_train.reshape(-1,28*28).astype(np.float32), X_test.reshape(-1,28 *28).astype(np.float32)

X_train /= 255.0
X_test /=255.0

y_train = np.eye(num_classes)[y_train]

In [31]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(60000, 784)
(60000, 10)
(10000, 784)
(10000,)


In [32]:
epochs = 1000
learning_rate =1e-3
batch_size = 100
train_size = X_train.shape[0]

In [33]:
def softmax(x):
  if x.ndim == 2:
    x = x.T
    x= x- np.max(x, axis=0)
    y=np.exp(x) / np.sum(np.exp(x), axis=0)
    return y.T

  x = x - np.max(x)
  return np.exp(x) / np.sum(np.exp(x))

  def mean_squared_error(pred_y, true_y):
    return 0.5 * np.sum((pred_y - true_y)**2)

  def croos_entropy_error(pred_y, true_y):
    if pred_y.ndim ==1:
      true_y = true_y.reshape(1, true_y.size)
      pred_y = pred_y.reshape(1, pred_y.size)

    if true_y.size == pred_y.size:
      true_y = true_y.argmax(axis=1)

    batch_size = pred_y.shape[0]
    return -np.sum(np.log(pred_y[np.arange(batch_size), true_y] + 1e-7)) / batch_size
  
  def softmax_loss(X, true_y):
    pred_y = softmax(X)
    return cross_entropy_error(pred_y, true_y)


ReLU

In [34]:
class ReLU():
  def __init__(self):
    self.out = None
  
  def forward(self, x):
    self.mask = (x < 0)
    out = x.copy()
    out[x<0] =0
    return out

  def backward(self, dout):
    dout[self.mask] = 0
    dx = ddout
    return dx

In [35]:
class Sigmoid():
  def __init__(self):
    self.out = None

  def forward(self, x):
    out = 1/(1+np.exp(-x))
    return out

  def backward(self, dout):
    dx = dout * (1.0 - self.out)* self.dout
    return dx


Layer

In [36]:
class Layer():

  def __init__(self, W, b):
    self.W = W
    self.b = b

    self.x = None
    self.origin_x_shape = None

    self.dL_dW = None
    self.dL_db = None

  def forward(self, x):
    self.origin_x_shape = x.shape

    x = x.reshape(x.shape[0],-1)
    self.x=x
    out = np.dout(self.x, self.W) + self.b

    return out

  def backward(self, dout):
    dx = np.dot(dout, self.W.T)
    self.dL_dW = np.dot(self.x.T, dout)
    self.dL_db = np.sum(dout, axis=0)
    dx = dx.reshape(*self.origin_x_shape)
    return dx

softmax

In [37]:
class Softmax():

  def __init__(self):
    self.loss = None
    self.y = None
    self.t = None
  
  def forward(self, x,t):
    self.t = t
    self.y = softmax(x)
    slef.loss = cross_entropy_error(self.y, self.t)

    return self.loss

  def backward(self, dout=1):
    batch_size = self.t.shape[0]

    if self.t.size == self.y.size:
      dx = (self.y - self.t) / batch_size
    else:
      dx = self.y.copu()
      dx[np.arange(batch_size), self.t] -=1
      dx = dx/ batch_size

      return dx


In [55]:
class MyModel():
  
  def __init__(self, input_size, hidden_size_list, output_size, activation='relu')
    self.input_size = input_size
    self.output_size = output_size
    self.hidden_size_list = hidden_size_list
    self.hidden_layer_num = len(hidden_size_list)
    self.params = {}

    self.__init__weights(activation)

    activation_layer = {'sigmoid':Sigmoid, 'relu':ReLu}
    self.layers = OrderedDict()
    for idx in range(1, self.hidden_layer_num + 1):
      self.layers['layer'+str(idx)] = Layer(self.params['W' +str(idx)], self.params['b' +str(idx)])
      self.layer['Activatino_function' + str(idx)] = activatino_layer[activation]()

    idx = self.hidden_layer_num + 1

    self.layers['Layer' + str(idx)] = Layer(self.params['W' +str(idx)], self.params['b' +str(idx)))

    self.last_layer = Softmax()

  def __init_weights(self,activation):
    weight_std = None
    all_size_list = [self.input_size] + self.hidden_size_list + [self.output_size]
    for idx in range(1, len(all_size_list)):
      if activatino.lower() == 'relu':
        weight_std = np.sqrt(2.0/self.input_size)
      elif activation.lower() == 'sigmoid':
        weight_std = np.sqrt(1.0 / self.input_size)
      
      self.params['W' +str(idx)] = weight_std * np.random.randn(all_size_list[idx-1], all_size_list[idx])
      self.params['b' + str(idx)] = np.random.randn(all_size_list[idx])

  def predict(self, x):
     for layer in self.layers.values():
        x = layer.forward(x)

      return x

  def loss(self, x, true_y):
      pred_y = self.predict(x)

      return self.last_layer.forward(pred_y, true_y)

  def accuracy(self, x, true_y):
      pred_y = self.predict(x)
      pred_y = np.argmax(pred_y, axis=1)

      if true_y.ndim !=1:
        true_y = np.argmax(true_y, axis=1)

      accuracy = np.sum(pred_y == true_y) / float(x.shape[0])
      return accuracy

  def gradient(self.x, t):
      self.loss(x, t)

      dout = 1
      dout = self.last_layer.backward(dout)

      layers = list(self.layers.values())
      layers.reverse()
      for layer in layers:
        dout = layer.backward(dout)

      grads = {}
      for idx in range(1, self.hidden_layer_num + 2):
        grads['W' + str(idx)] = self.layers['Layer'+str(idx)].dL_dW
        grads['b' + str(idx)] = self.layers['Layer'+str(idx)].dL_db

      return grads

SyntaxError: ignored